### ISSUE TITLE
ruxg.py line 413

### ISSUE THREAD

**Issue by yass987** [sibirbil/RuleDiscovery#1]
Issue:
The line self.ruleLengthPerSample = np.mean(rule_lengths) assigns the mean value of rule_lengths to the entire array self.ruleLengthPerSample. However, the intention seems to assign this mean value to a specific index within self.ruleLengthPerSample.

Proposed Correction:
self.ruleLengthPerSample[sindx] = np.mean(rule_lengths). This change ensures the mean value is placed at the intended index within the array

**Comment by tabearoeber** [comment]
Thank you @yass987 for mentioning this. We have corrected the mistake in [f6d46d8](https://github.com/sibirbil/RuleDiscovery/commit/f6d46d8078b1a1da6775d9169b75bbbbe0c56e6b).
